'use client'

import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { ArrowLeft, Shield, Eye, Lock, Database, Mail, AlertTriangle, Users, Settings, Bell, Trash2, Globe, UserCheck } from 'lucide-react'

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-slate-50/50">
      {/* Header */}
      <div className="border-b border-gray-200/60 bg-white/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center text-gray-600 hover:text-gray-900 transition-colors">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Link>          <div className="flex items-center gap-2">
            <Shield className="w-5 h-5 text-blue-500" />
            <span className="text-sm font-medium text-gray-900">Privacy Protected</span>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">        {/* Page Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-gray-200 bg-gray-100 text-gray-700 text-xs font-medium mb-4">
            <Eye className="w-3 h-3" />
            Privacy Document
          </div>
          <h1 className="text-4xl font-bold mb-4 text-gray-900">Privacy Policy</h1>
          <p className="text-gray-600">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>        {/* Privacy Notice Banner */}
        <div className="bg-gradient-to-r from-blue-50 to-blue-50 border border-blue-200/60 rounded-xl p-6 mb-8">
          <div className="flex items-start">
            <Lock className="w-6 h-6 text-blue-600 mr-4 mt-1 flex-shrink-0" />
            <div>
              <h3 className="text-blue-900 font-semibold mb-2">Your Privacy is Our Priority</h3>
              <p className="text-blue-800 leading-relaxed">
                Ecomply is designed with privacy-first principles. We minimize data collection, encrypt all communications, 
                and never store your sensitive document content permanently. This policy explains exactly how we protect your information.
              </p>
            </div>
          </div>
        </div>{/* Privacy Content */}
        <Card className="bg-white border border-gray-200/60 mb-8 rounded-xl">
          <CardContent className="p-8">
            <div className="prose prose-slate max-w-none">
                {/* Section 1 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Database className="w-5 h-5 text-blue-600" />
                  </div>
                  Information We Collect
                </h2>
                
                <h3 className="text-lg font-medium text-gray-900 mb-3 mt-6">Account Information</h3>
                <p className="text-gray-700 leading-relaxed mb-4">
                  When you create an Ecomply account, we collect:
                </p>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                  <li>Email address (for account creation and notifications)</li>
                  <li>Encrypted password (we cannot see your actual password)</li>
                  <li>Account creation date and last login information</li>
                </ul>

                <h3 className="text-lg font-medium text-gray-900 mb-3 mt-6">Document Analysis Data</h3>
                <p className="text-gray-700 leading-relaxed mb-4">
                  When you use our compliance analysis service:
                </p>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                  <li>Document content (processed temporarily, not stored permanently)</li>
                  <li>Analysis results and compliance scores</li>
                  <li>Improvement recommendations generated by our AI</li>
                  <li>Usage patterns to improve our service quality</li>
                </ul>

                <h3 className="text-lg font-medium text-gray-900 mb-3 mt-6">Technical Information</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                  <li>IP address and browser information</li>
                  <li>Device type and operating system</li>
                  <li>Service usage statistics and performance metrics</li>
                </ul>
              </section>

              {/* Section 2 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Settings className="w-5 h-5 text-blue-600" />
                  </div>
                  How We Use Your Information
                </h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  We use your information exclusively for:
                </p>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                  <li>Providing document compliance analysis services</li>
                  <li>Maintaining and improving our AI analysis capabilities</li>
                  <li>Authenticating your account and ensuring security</li>                  <li>Communicating important service updates or issues</li>
                  <li>Responding to your support requests and inquiries</li>
                  <li>Ensuring compliance with Philippine data protection laws</li>
                </ul>
                  <div className="bg-gradient-to-r from-blue-50 to-blue-50 border border-blue-200/60 rounded-xl p-4 mt-6">
                  <div className="flex items-start">
                    <Database className="w-5 h-5 text-blue-600 mr-3 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="text-blue-900 font-medium mb-2">Document Processing Policy</p>
                      <p className="text-blue-800 text-sm leading-relaxed">
                        Your document content is processed in memory only and is not stored permanently on our servers. 
                        After analysis completion, document content is automatically purged from our systems.
                      </p>
                    </div>
                  </div>
                </div>
              </section>

              {/* Section 3 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Shield className="w-5 h-5 text-blue-600" />
                  </div>
                  Data Security and Protection
                </h2>
                
                <h3 className="text-lg font-medium text-gray-900 mb-3">Technical Safeguards</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
                  <li>Industry-standard TLS encryption for all data transmission</li>
                  <li>Secure cloud infrastructure with regular security audits</li>
                  <li>Multi-factor authentication options for account security</li>
                  <li>Regular security updates and vulnerability assessments</li>
                </ul>

                <h3 className="text-lg font-medium text-gray-900 mb-3">Data Handling Practices</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                  <li>Minimal data collection - we only collect what&apos;s necessary</li>
                  <li>Temporary processing - document content is not permanently stored</li>
                  <li>Access controls - only authorized personnel can access user data</li>
                  <li>Regular data purging - unnecessary data is automatically deleted</li>
                </ul>
              </section>

              {/* Section 4 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Users className="w-5 h-5 text-blue-600" />
                  </div>
                  Data Sharing and Third Parties
                </h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  We do not sell, trade, or rent your personal information to third parties. We may share limited data only in these circumstances:
                </p>
                
                <h3 className="text-lg font-medium text-gray-900 mb-3">Service Providers</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
                  <li>Supabase (authentication and database services)</li>
                  <li>Google Gemini AI (document analysis processing)</li>
                  <li>Vercel (hosting and deployment platform)</li>
                </ul>

                <h3 className="text-lg font-medium text-gray-900 mb-3">Legal Requirements</h3>
                <p className="text-gray-700 leading-relaxed">
                  We may disclose your information if required by law, legal process, or government request in accordance with Philippine law and international legal cooperation agreements.
                </p>
              </section>

              {/* Section 5 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <UserCheck className="w-5 h-5 text-blue-600" />
                  </div>
                  Your Rights and Choices
                </h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Under Philippine data protection laws, you have the following rights:
                </p>
                
                <div className="grid md:grid-cols-2 gap-4">                  <div className="bg-gray-50 border border-gray-200/60 rounded-xl p-4">
                    <h4 className="font-medium text-gray-900 mb-2">Access Rights</h4>
                    <p className="text-gray-700 text-sm">Request a copy of your personal data we hold</p>
                  </div>
                  <div className="bg-gray-50 border border-gray-200/60 rounded-xl p-4">
                    <h4 className="font-medium text-gray-900 mb-2">Correction Rights</h4>
                    <p className="text-gray-700 text-sm">Update or correct inaccurate information</p>
                  </div>
                  <div className="bg-gray-50 border border-gray-200/60 rounded-xl p-4">
                    <h4 className="font-medium text-gray-900 mb-2">Deletion Rights</h4>
                    <p className="text-gray-700 text-sm">Request deletion of your account and data</p>
                  </div>
                  <div className="bg-gray-50 border border-gray-200/60 rounded-xl p-4">
                    <h4 className="font-medium text-gray-900 mb-2">Portability Rights</h4>
                    <p className="text-gray-700 text-sm">Export your data in a machine-readable format</p>
                  </div>
                </div>
              </section>

              {/* Section 6 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Eye className="w-5 h-5 text-blue-600" />
                  </div>
                  Cookies and Tracking
                </h2><p className="text-gray-700 leading-relaxed mb-4">
                  Ecomply uses minimal cookies and tracking technologies:
                </p>
                
                <h3 className="text-lg font-medium text-gray-900 mb-3">Essential Cookies</h3>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
                  <li>Authentication tokens (required for login functionality)</li>
                  <li>Session management (maintains your login state)</li>
                  <li>Security tokens (prevents unauthorized access)</li>
                </ul>

                <h3 className="text-lg font-medium text-gray-900 mb-3">Analytics</h3>
                <p className="text-gray-700 leading-relaxed">
                  We collect anonymized usage statistics to improve our service. This data cannot be used to identify individual users.
                </p>
              </section>

              {/* Section 7 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Trash2 className="w-5 h-5 text-blue-600" />
                  </div>
                  Data Retention
                </h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  We retain your information for the following periods:
                </p>
                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                  <li><strong>Account Information:</strong> Until you request deletion or close your account</li>
                  <li><strong>Document Content:</strong> Immediately deleted after analysis completion</li>
                  <li><strong>Analysis Results:</strong> Stored for your reference until account deletion</li>
                  <li><strong>Support Communications:</strong> Retained for 2 years for service improvement</li>
                  <li><strong>Legal Data:</strong> Retained as required by Philippine law</li>
                </ul>
              </section>

              {/* Section 8 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Globe className="w-5 h-5 text-blue-600" />
                  </div>
                  International Data Transfers
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  Your data may be processed in data centers outside the Philippines. We ensure that all international data transfers comply with Philippine data protection laws and include appropriate safeguards such as standard contractual clauses and adequacy decisions.
                </p>
              </section>              {/* Section 9 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Bell className="w-5 h-5 text-blue-600" />
                  </div>
                  Changes to This Policy
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  We may update this Privacy Policy from time to time. We will notify you of any material changes by email or through a prominent notice on our service. Your continued use of Ecomply after any changes constitutes your acceptance of the updated policy.
                </p>
              </section>              {/* Section 10 */}              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4 flex items-center">
                  <div className="w-10 h-10 bg-blue-50 rounded-full flex items-center justify-center mr-3">
                    <Mail className="w-5 h-5 text-blue-600" />
                  </div>
                  Contact Information
                </h2>
                <p className="text-gray-700 leading-relaxed mb-6">
                  If you have any questions about this Privacy Policy or wish to exercise your data protection rights, please contact us:
                </p>
                  <div className="space-y-4">                  <div className="bg-gradient-to-r from-blue-50 to-blue-50 border border-blue-200/60 rounded-xl p-4 flex items-center">
                    <Mail className="w-5 h-5 text-blue-600 mr-3" />
                    <div>
                      <p className="text-gray-900 font-medium">Privacy Officer</p>
                      <p className="text-gray-700">arisantonioco@gmail.com</p>
                    </div>
                  </div>
                  
                  <div className="bg-gray-50 border border-gray-200/60 rounded-xl p-4">
                    <p className="text-gray-900 font-medium mb-2">Data Subject Requests</p>
                    <p className="text-gray-700 text-sm leading-relaxed">
                      For requests related to your personal data (access, correction, deletion, portability), 
                      please include &quot;Data Subject Request&quot; in your email subject line. We will respond within 30 days as required by Philippine law.
                    </p>
                  </div>
                </div>
              </section>

              {/* Compliance Notice */}
              <section>                <div className="bg-gradient-to-r from-purple-50 to-purple-50 border border-purple-200/60 rounded-xl p-6">
                  <div className="flex items-start">
                    <AlertTriangle className="w-6 h-6 text-purple-600 mr-4 mt-1 flex-shrink-0" />
                    <div>
                      <h3 className="text-purple-900 font-semibold mb-2">Compliance Notice</h3>
                      <p className="text-purple-800 leading-relaxed">
                        This Privacy Policy is designed to comply with the Data Privacy Act of 2012 (Republic Act No. 10173) 
                        and other applicable Philippine data protection regulations. We are committed to protecting your privacy 
                        rights and maintaining the highest standards of data security.
                      </p>
                    </div>
                  </div>
                </div>
              </section>

            </div>
          </CardContent>
        </Card>        {/* Footer Actions */}
        <div className="flex flex-col sm:flex-row gap-4 justify-between items-center">
          <Link href="/legal/terms">
            <Button variant="outline" className="text-blue-600 hover:bg-blue-50 bg-white hover:border-blue-300 transition-all duration-200">
              View Terms of Service
            </Button>
          </Link>
          <Link href="/auth">
            <Button className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white transition-all duration-200">
              Start Using Ecomply Securely
            </Button>
          </Link>
        </div>
      </div>
    </div>
  )
}
